'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const migration=read('supabase/migrations/20261004100000_v3_community_moderation.sql');
const rollback=read('supabase/rollback/20261004100000_v3_community_moderation_down.sql');
const model=read('static/js/community/community-model.js');const admin=read('admin-reports.html');
const diagnosis=read('diagnosis.html');const channel=read('channel.html');const index=read('index.html');const post=read('post.html');
const draft=read('static/js/community/question-draft.js');const legacy=read('search_result.html');
const archive=read('docs/v3-archive-policy.md');const preview=read('docs/v3-preview-checklist.md');const contract=read('docs/v3-community-ops-contract.md');
let passed=0;function test(name,fn){try{fn();passed++}catch(error){error.message=`${name}: ${error.message}`;throw error}}

test('moderator role is database backed',()=>{assert.match(migration,/create table if not exists public\.community_user_roles/);assert.match(migration,/role in \('moderator'\)/)});
test('role writes are unavailable to browser roles',()=>{assert.match(migration,/revoke all on public\.community_user_roles from public, anon, authenticated/);assert.doesNotMatch(migration,/grant (?:insert|update|delete)[^;]*community_user_roles/i)});
test('role is not based on email metadata or local storage',()=>{for(const source of [migration,model,admin])assert.doesNotMatch(source,/user_metadata|localStorage|@(?:gmail|naver|kfarmai)/i)});
test('role RLS exposes only own row',()=>assert.match(migration,/community_user_roles_self_read[\s\S]*user_id = auth\.uid\(\)/));
test('report statuses are explicit',()=>{for(const status of ['pending','reviewed','dismissed','actioned'])assert.match(migration,new RegExp(`'${status}'`))});
test('report owners and moderators have distinct read contract',()=>assert.match(migration,/auth\.uid\(\) = reporter_user_id or public\.community_is_moderator\(\)/));
test('only moderator can update reports',()=>assert.match(migration,/community_reports_moderator_update[\s\S]*community_is_moderator/));
test('queue rejects non moderators',()=>assert.match(migration,/moderator_required[\s\S]*42501/));
test('queue batches preview and caps 100',()=>{assert.match(migration,/left join public\.posts/);assert.match(migration,/left join public\.comments/);assert.match(migration,/least\(greatest\(page_limit, 1\), 100\)/)});
test('moderation does not delete content',()=>assert.doesNotMatch(migration,/delete\s+from\s+public\.(posts|comments)/i));
test('rollback restores owner-only report policy',()=>assert.match(rollback,/community_reports_owner_read[\s\S]*auth\.uid\(\) = reporter_user_id/));
test('admin page is noindex',()=>assert.match(admin,/noindex,nofollow/));
test('admin page checks session and DB moderator role',()=>{assert.match(admin,/auth\.getSession/);assert.match(admin,/KFCommunity\.isModerator/)});
test('admin page uses one queue RPC contract',()=>assert.match(admin,/KFCommunity\.reportQueue\(client,filter,100,0\)/));
test('admin actions only change review status',()=>{for(const value of ['reviewed','dismissed','actioned'])assert.match(admin,new RegExp(value));assert.doesNotMatch(admin,/from\(['"]posts['"]\).*delete/)});
test('admin renders remote content with textContent',()=>{assert.match(admin,/el\.textContent=text/);assert.doesNotMatch(admin,/target_preview[^\n]*innerHTML/)});
test('MY admin link is hidden by default',()=>assert.match(index,/id="myAdminReports"[^>]*hidden/));
test('MY admin link uses DB role check',()=>assert.match(index,/KFCommunity\.isModerator\(_sb\)/));
test('MY has posts saved blocks and account settings',()=>{for(const label of ['내가 쓴 글','저장한 글','차단한 사용자 관리','계정 설정'])assert.match(index,new RegExp(label))});
test('saved posts avoid per-post requests',()=>{assert.match(index,/from\('post_bookmarks'\)[\s\S]*\.limit\(100\)/);assert.match(index,/from\('posts'\)[\s\S]*\.in\('id',ids\)/)});
test('AI draft source and structured fields are stable',()=>{for(const token of ["source: 'ai_diagnosis'",'crop: safeResult.crop','symptoms: safeResult.symptoms','suggestedTags: safeResult.tags','summary:'])assert.match(diagnosis,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('AI photo draft uses local IndexedDB',()=>{assert.match(draft,/indexedDB\.open/);assert.match(diagnosis,/KFQuestionDraft\.saveImage\(capturedFile\)/)});
test('AI draft does not upload before navigation',()=>{const flow=diagnosis.match(/async function shareToCommunity[\s\S]*?\/\* ── Pull/)?.[0]||'';assert.doesNotMatch(flow,/storage|\.upload\(/)});
test('channel consumes crop symptoms tags and image draft',()=>{for(const token of ['pending.crop','pending.symptoms','pending.suggestedTags','pending.imageDraftId','KFQuestionDraft.loadImage'])assert.match(channel,new RegExp(token.replace(/[.]/g,'\\.')))});
test('AI wording separates observations and reference',()=>{assert.match(channel,/관찰한 증상:/);assert.match(channel,/AI 참고 확인에서 정리된 내용:/)});
test('draft is never auto published',()=>{const flow=channel.match(/async function applyPendingQuestionQuery[\s\S]*?function makePendingQuestionPreset/)?.[0]||'';assert.doesNotMatch(flow,/from\('posts'\)|\.insert\(/)});
test('cancel removes local image draft',()=>assert.match(channel,/closeWriteModal[\s\S]*KFQuestionDraft\.removeImage/));
test('draft expires within one day',()=>assert.match(draft,/24 \* 60 \* 60 \* 1000/));
test('image is canvas re-encoded before upload',()=>{assert.match(draft,/drawImage/);assert.match(draft,/canvasBlob/);assert.match(channel,/prepareForUpload\(file\)/);assert.match(index,/prepareForUpload\(file\)/)});
test('original image filename is not uploaded',()=>{assert.match(draft,/genericName/);assert.doesNotMatch(channel,/file\.name[^\n]*\.upload/)});
test('failed post insert removes uploaded objects',()=>{assert.match(channel,/cleanupPostUploads\(uploaded\.paths\)/);assert.match(index,/cleanupPostUploads\(uploaded\.paths\)/)});
test('post deletion cleans associated storage',()=>assert.match(post,/storagePaths[\s\S]*from\('post-images'\)\.remove/));
test('legacy Render endpoint is removed',()=>assert.doesNotMatch(legacy,/onrender\.com|\/api\/search/));
test('legacy search redirects query to V3 search',()=>{assert.match(legacy,/location\.replace/);assert.match(legacy,/target\.searchParams\.set\('q',query\)/)});
test('legacy search has noindex and canonical',()=>{assert.match(legacy,/noindex,follow/);assert.match(legacy,/rel="canonical"/)});
test('archive policy covers all exposure surfaces',()=>{for(const label of ['ACTIVE','HIDDEN','ARCHIVE','REMOVE-LATER','Navigation','Feed','통합검색','Sitemap'])assert.match(archive,new RegExp(label))});
test('plant share archive policy is explicit',()=>{for(const phrase of ['나눔·직거래','신규 글쓰기','Feed 제외','통합검색 제외'])assert.match(archive,new RegExp(phrase))});
test('preview checklist has ordered migrations and rollback gate',()=>{assert.match(preview,/20261004100000_v3_community_moderation\.sql/);for(const section of ['Migration order','Preview deploy order','Smoke test','Rollback','Preview → Production gate'])assert.match(preview,new RegExp(section))});
test('photo privacy contract covers EXIF GPS and orphan cleanup',()=>{for(const term of ['EXIF','GPS','orphan','게시 확정 전 Storage 업로드는 없다'])assert.match(contract,new RegExp(term))});
test('frontend has no service role secret',()=>{for(const source of [admin,diagnosis,channel,index,post,model,draft])assert.doesNotMatch(source,/service[_-]?role/i)});

process.stdout.write(`Phase 4C community ops contracts: ${passed}/${passed} PASS\n`);
