'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const legacy=JSON.parse(read('data/agri-input-categories.json'));const taxonomy=JSON.parse(read('data/agri-input-taxonomy.json'));
const mfg=read('mfg.html');const home=read('index.html');const audit=read('docs/v3-phase5a-agri-input-audit.md');
let passed=0;function test(name,fn){try{fn();passed++}catch(error){error.message=`${name}: ${error.message}`;throw error}}
const canonical=taxonomy.canonicalCategories;const ids=canonical.map(item=>item.id);const mapping=taxonomy.legacyMapping;
const smart=canonical.find(item=>item.id==='smart-agriculture');const smartfarm=smart.children.find(item=>item.id==='smartfarm');const aquafarm=smart.children.find(item=>item.id==='land-aquafarm');

test('legacy eight-category data remains intact',()=>assert.equal(legacy.length,8));
test('canonical model has exactly six top categories',()=>assert.equal(canonical.length,6));
test('canonical category ids are unique',()=>assert.equal(new Set(ids).size,6));
test('six required category names are exact',()=>assert.deepEqual(canonical.map(item=>item.name),['종자·육묘','토양·영양','작물보호','시설·관수','스마트농업','원예·도구']));
test('every canonical category has summary and topics',()=>canonical.forEach(item=>{assert.ok(item.summary);assert.ok(item.topics.length)}));
test('every legacy id has one compatibility mapping',()=>legacy.forEach(item=>assert.equal(mapping.filter(row=>row.legacyId===item.id).length,1,item.id)));
test('mapping never points outside canonical ids',()=>mapping.forEach(row=>assert.ok(ids.includes(row.canonicalId),row.legacyId)));
test('santo and fertilizer merge into soil nutrition',()=>{for(const id of ['santo','fertilizer'])assert.equal(mapping.find(row=>row.legacyId===id).canonicalId,'soil-nutrition')});
test('machinery safety is hidden as a top category',()=>{const row=mapping.find(item=>item.legacyId==='machinery-safety');assert.equal(row.action,'HIDE');assert.ok(!ids.includes('machinery-safety'))});
test('machinery topics are distributed safely',()=>assert.deepEqual(mapping.find(item=>item.legacyId==='machinery-safety').distributedTags,['시설 안전','작물보호','원예 안전']));
test('smart agriculture has two child areas',()=>assert.deepEqual(smart.children.map(item=>item.id),['smartfarm','land-aquafarm']));
test('smartfarm includes required environment topics',()=>{for(const term of ['온도','습도','CO₂','일사','토양수분','EC','pH','관수','양액','센서','환경제어','자동화','에너지','EMS','시설재배','데이터 활용'])assert.ok(smartfarm.topics.includes(term),term)});
test('aquafarm includes required water topics',()=>{for(const term of ['수온','용존산소','DO','pH','염분','ORP','암모니아','순환여과','RAS','수처리','펌프','산소공급','센서','모니터링','자동제어','에너지','EMS','육상양식'])assert.ok(aquafarm.topics.some(topic=>topic.includes(term)),term)});
test('smartfarm has useful seed entries',()=>assert.equal(smartfarm.entries.length,5));
test('aquafarm has useful seed entries',()=>assert.equal(aquafarm.entries.length,6));
test('seed entries are explanatory rather than empty placeholders',()=>[...smartfarm.entries,...aquafarm.entries].forEach(entry=>{assert.ok(entry.title.length>1);assert.ok(entry.description.length>20)}));
test('taxonomy explicitly disallows product ranking',()=>assert.equal(taxonomy.principles.productRanking,false));
test('taxonomy explicitly disallows realtime claims',()=>assert.equal(taxonomy.principles.realtimeClaims,false));
test('taxonomy has no fake products or measured values',()=>assert.doesNotMatch(JSON.stringify(taxonomy),/productId|price|stock|실시간\s*(?:수온|DO|pH)|구매하기|장바구니|결제/i));
test('taxonomy has no private project wording',()=>assert.doesNotMatch(JSON.stringify(taxonomy),/BTS|내부과제|비공개 사업/i));
test('hub title and H1 use the production taxonomy name',()=>{assert.match(mfg,/<title>농자재·스마트농업/);assert.match(mfg,/<h1>농자재·스마트농업<\/h1>/)});
test('hub grid is rendered from canonical data',()=>{assert.match(mfg,/id="canonicalCategoryGrid"/);assert.match(mfg,/canonicalCategoryData\.map/)});
test('legacy data and canonical taxonomy are both loaded',()=>{assert.match(mfg,/agri-input-categories\.json/);assert.match(mfg,/agri-input-taxonomy\.json/)});
test('legacy category query aliases remain supported',()=>{for(const alias of ['santo','seed','fertilizer','irrigation-facility','home-gardening-tools','smartfarm','machinery-safety'])assert.match(mfg,new RegExp(`['"]?${alias.replace('-','\\-')}['"]?\\s*:`))});
test('smartfarm legacy URL opens smartfarm child',()=>assert.match(mfg,/rawSelectedId === 'smartfarm'.*return 'smartfarm'/));
test('aquafarm aliases open land aquafarm child',()=>assert.match(mfg,/rawSelectedId === 'aquafarm'.*rawSelectedId === 'land-aquafarm'/));
test('company directory follows the information main',()=>assert.ok(mfg.indexOf('</main>')<mfg.indexOf('id="companyDirectorySection"')));
test('company directory is collapsed by default',()=>assert.match(mfg,/<details class="company-directory" id="companyDirectorySection">/));
test('category layout never moves company content ahead',()=>{const flow=mfg.match(/function arrangeMfgCategoryLayout[\s\S]*?function getSelectedSmartArea/)?.[0]||'';assert.doesNotMatch(flow,/companySearch|companyGrid|companySource/)});
test('hub has no preparation-only core CTA',()=>{const links=[...mfg.matchAll(/<a\b[^>]*>([\s\S]*?)<\/a>/g)].map(match=>match[1].replace(/<[^>]+>/g,''));assert.equal(links.filter(text=>/준비중|준비 중/.test(text)).length,0)});
test('hub avoids contest prototype copy in core markup',()=>assert.doesNotMatch(mfg,/공모전|MVP|시제품/));
test('query detail pages are noindex follow',()=>assert.match(mfg,/robots\.content = 'noindex,follow'/));
test('hub declares canonical URL and description',()=>{assert.match(mfg,/rel="canonical" href="https:\/\/kfarmai\.com\/mfg\.html"/);assert.match(mfg,/<meta name="description"/)});
test('home search contains all six canonical labels',()=>{for(const label of ['종자·육묘','토양·영양','작물보호','시설·관수','스마트농업','원예·도구'])assert.match(home,new RegExp(`label:'${label}'`))});
test('home search includes smartfarm and aquafarm routes',()=>{assert.match(home,/area=smartfarm/);assert.match(home,/area=land-aquafarm/)});
test('home search covers specialist terms',()=>{for(const term of ['스마트팜','EC 센서','DO','RAS','수질','육상양식'])assert.match(home,new RegExp(term))});
test('old machinery category is absent from primary search entries',()=>{const block=home.match(/const AGRI_LINKS=\[[\s\S]*?\n\];/)?.[0]||'';assert.doesNotMatch(block,/label:'농기계·안전용품'/)});
test('audit records all required disposition states',()=>{for(const state of ['KEEP','MERGE','MOVE','HIDE','ARCHIVE'])assert.match(audit,new RegExp(state))});
test('audit separates agri info inputs and community roles',()=>{for(const label of ['농업정보','농자재·스마트농업','커뮤니티'])assert.match(audit,new RegExp(label))});
test('audit preserves dedicated legacy pages',()=>{for(const page of ['santo.html','seed.html','cpa.html','fert.html'])assert.match(audit,new RegExp(page.replace('.','\\.')))});
test('audit defines information-first vendor policy',()=>assert.match(audit,/정보 → 기술·분류 → 필요한 경우 업체 공식정보/));

process.stdout.write(`Phase 5A smart agriculture contracts: ${passed}/${passed} PASS\n`);
