'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const read=file=>fs.readFileSync(path.join(root,file),'utf8');const exists=file=>fs.existsSync(path.join(root,file));
const rasPath='kb/ras-recirculating-aquaculture.html';const waterPath='kb/land-aquaculture-water-quality.html';
const ras=read(rasPath);const water=read(waterPath);const pages=[ras,water];const mfg=read('mfg.html');const sitemap=read('sitemap.xml');const taxonomy=JSON.parse(read('data/agri-input-taxonomy.json'));const registry=JSON.parse(read('data/agri-official-sources.json'));const loader=read('static/js/agri/official-source-registry.js');
const sourceIds=new Set(registry.sources.map(source=>source.id));const aquafarm=taxonomy.canonicalCategories.find(item=>item.id==='smart-agriculture').children.find(item=>item.id==='land-aquafarm');
let passed=0;function test(name,fn){try{fn();passed++}catch(error){error.message=name+': '+error.message;throw error}}
const titleOf=page=>page.match(/<title>([^<]+)<\/title>/)?.[1]||'';const canonicalOf=page=>page.match(/<link rel="canonical" href="([^"]+)"/)?.[1]||'';
const idsOf=page=>(page.match(/data-official-source-ids="([^"]+)"/)?.[1]||'').split(',').filter(Boolean);

test('RAS priority page exists',()=>assert.ok(exists(rasPath)));
test('water quality priority page exists',()=>assert.ok(exists(waterPath)));
test('priority page titles are unique',()=>assert.notEqual(titleOf(ras),titleOf(water)));
test('titles describe the intended subjects',()=>{assert.match(titleOf(ras),/RAS 순환여과양식/);assert.match(titleOf(water),/육상양식 수질관리/)});
test('canonical URLs use the public domain',()=>{assert.equal(canonicalOf(ras),'https://kfarmai.com/kb/ras-recirculating-aquaculture.html');assert.equal(canonicalOf(water),'https://kfarmai.com/kb/land-aquaculture-water-quality.html')});
test('canonical URLs never use localhost',()=>pages.forEach(page=>assert.doesNotMatch(canonicalOf(page),/localhost|127\.0\.0\.1/)));
test('each page has one H1',()=>pages.forEach(page=>assert.equal((page.match(/<h1\b/g)||[]).length,1)));
test('each page has meta and OpenGraph descriptions',()=>pages.forEach(page=>{assert.match(page,/<meta name="description" content="[^"]+">/);assert.match(page,/<meta property="og:description" content="[^"]+">/)}));
test('each page has Article structured data',()=>pages.forEach(page=>assert.match(page,/"@type":"Article"/)));
test('each page has BreadcrumbList structured data',()=>pages.forEach(page=>assert.match(page,/"@type":"BreadcrumbList"/)));
test('all JSON-LD blocks parse as JSON',()=>pages.forEach(page=>[...page.matchAll(/<script type="application\/ld\+json">\s*([\s\S]*?)\s*<\/script>/g)].forEach(match=>JSON.parse(match[1]))));
test('each page has semantic visible breadcrumb',()=>pages.forEach(page=>assert.match(page,/<nav class="breadcrumb" aria-label="현재 위치">/)));
test('each page connects official source IDs',()=>pages.forEach(page=>assert.ok(idsOf(page).length>=2)));
test('page source IDs all exist in Registry',()=>pages.flatMap(idsOf).forEach(id=>assert.ok(sourceIds.has(id),id)));
test('source renderer loads the Registry',()=>assert.match(loader,/fetch\('\/data\/agri-official-sources\.json'/));
test('source renderer uses safe DOM text',()=>{assert.match(loader,/textContent/);assert.doesNotMatch(loader,/innerHTML/)});
test('source renderer displays source metadata and license state',()=>{for(const token of ['source.institution','source.title','source.publishedAt','source.checkedAt','needs-review'])assert.ok(loader.includes(token),token)});
test('RAS official evidence is connected',()=>assert.ok(idsOf(ras).includes('nifs-2022-climate-aquaculture-ras')));
test('RAS treatment structure covers official evidence scope',()=>{for(const term of ['고형물 제거','용존유기물 처리','pH·이온 조절','생물여과','질산화·탈질','살균','용존가스','재순환'])assert.ok(ras.includes(term),term)});
test('RAS links core water quality',()=>{for(const term of ['수온','용존산소(DO)','pH','염분','암모니아성','아질산성','질산성'])assert.ok(ras.includes(term),term)});
test('water page covers required measurements',()=>{for(const term of ['수온','용존산소(DO)','pH','염분','암모니아성질소','아질산성질소','질산성질소'])assert.ok(water.includes(term),term)});
test('water quality evidence is connected',()=>{for(const id of ['nifs-water-quality-guidance-2024','nifs-2022-climate-aquaculture-ras'])assert.ok(idsOf(water).includes(id),id)});
test('priority pages link to each other',()=>{assert.match(ras,/href="\/kb\/land-aquaculture-water-quality\.html"/);assert.match(water,/href="\/kb\/ras-recirculating-aquaculture\.html"/)});
test('smart agriculture area links to both pages',()=>{for(const url of [rasPath,waterPath])assert.ok(mfg.includes(url),url)});
test('taxonomy is the internal-link source',()=>assert.deepEqual(aquafarm.contentLinks.map(item=>item.url),[rasPath,waterPath]));
test('sitemap contains exactly the two priority URLs',()=>{for(const url of [rasPath,waterPath])assert.equal(sitemap.split('https://kfarmai.com/'+url).length-1,1,url)});
test('ORP policy remains supplementary and held',()=>{assert.equal(aquafarm.topicPolicies.ORP.evidenceLevel,'supplementary');assert.equal(aquafarm.topicPolicies.ORP.seoEligibility,'hold')});
test('ORP has no independent page or sitemap URL',()=>{assert.equal(exists('kb/aquafarm-orp.html'),false);assert.doesNotMatch(sitemap,/orp/i)});
test('ORP is not a title H1 or independent section',()=>pages.forEach(page=>{assert.doesNotMatch(titleOf(page),/ORP/);assert.doesNotMatch(page,/<h1[^>]*>[^<]*ORP|<h2[^>]*>[^<]*ORP/)}));
test('pages avoid unsupported quantitative performance claims',()=>pages.forEach(page=>assert.doesNotMatch(page,/\d+(?:\.\d+)?\s*(?:mg\/L|ppm|%p|%|배|톤|kWh)/i)));
test('pages contain no vendor product or sales promotion',()=>pages.forEach(page=>assert.doesNotMatch(page,/구매하기|가격비교|장바구니|결제|추천 제품|최저가|생산량\s*\d/i)));
test('official material and kFarmAI explanation are distinct',()=>pages.forEach(page=>{assert.match(page,/kFarmAI 설명:/);assert.match(page,/<h2>관련 공식자료<\/h2>/)}));
test('unverified licenses are never called freely reusable',()=>pages.forEach(page=>assert.doesNotMatch(page,/자유\s*이용|상업적\s*이용\s*가능|변경\s*이용\s*가능/)));
test('pages provide no dead core links',()=>pages.forEach(page=>assert.doesNotMatch(page,/href="(?:#|javascript:|)"/i)));
test('heading hierarchy starts at H1 and never skips levels',()=>pages.forEach(page=>{const levels=[...page.matchAll(/<h([1-3])\b/g)].map(match=>Number(match[1]));assert.equal(levels[0],1);for(let i=1;i<levels.length;i++)assert.ok(levels[i]-levels[i-1]<=1)}));
test('legacy input detail pages remain present',()=>['santo.html','seed.html','cpa.html','fert.html'].forEach(file=>assert.ok(exists(file),file)));
test('only the two approved priority SEO page filenames exist',()=>{const names=fs.readdirSync(path.join(root,'kb')).filter(name=>/aquaculture|aquafarm|ras/i.test(name));assert.deepEqual(names.sort(),[path.basename(waterPath),path.basename(rasPath)].sort())});

process.stdout.write('Phase 5B-3 priority SEO contracts: '+passed+'/'+passed+' PASS\n');
