'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const registry=JSON.parse(read('data/agri-official-sources.json'));const taxonomy=JSON.parse(read('data/agri-input-taxonomy.json'));
const audit=read('docs/v3-phase5b2-official-source-audit.md');const home=read('index.html');const sources=registry.sources;const sourceIds=new Set(sources.map(item=>item.id));
const smart=taxonomy.canonicalCategories.find(item=>item.id==='smart-agriculture');const smartfarm=smart.children.find(item=>item.id==='smartfarm');const aquafarm=smart.children.find(item=>item.id==='land-aquafarm');
const allEvidence=[...(smartfarm.evidence||[]),...(aquafarm.evidence||[])];const allEvidenceIds=allEvidence.flatMap(item=>item.sourceIds||[]);const seoRefs=registry.seoCandidates.flatMap(item=>item.sourceIds||[]);
let passed=0;function test(name,fn){try{fn();passed++}catch(error){error.message=`${name}: ${error.message}`;throw error}}
const evidenceFor=(area,topic)=>area.evidence.find(item=>item.topic===topic)?.sourceIds||[];

test('registry path is declared by taxonomy',()=>assert.equal(taxonomy.sourceRegistry,'data/agri-official-sources.json'));
test('registry has eleven official sources',()=>assert.equal(sources.length,11));
test('institution source counts match the audit',()=>{const count=label=>sources.filter(item=>item.institution.includes(label)).length;assert.equal(count('농촌진흥청'),4);assert.equal(count('농림축산식품부'),2);assert.equal(count('해양수산부'),2);assert.equal(count('국립수산과학원'),3)});
test('official source ids are unique',()=>assert.equal(sourceIds.size,sources.length));
test('source ids use stable slug format',()=>sources.forEach(item=>assert.match(item.id,/^[a-z0-9]+(?:-[a-z0-9]+)*$/)));
test('source URLs are never missing',()=>sources.forEach(item=>assert.ok(item.url)));
test('source URLs are valid HTTPS URLs',()=>sources.forEach(item=>assert.equal(new URL(item.url).protocol,'https:')));
test('source URLs use approved official domains',()=>{const allowed=['rda.go.kr','nongsaro.go.kr','mafra.go.kr','nifs.go.kr','mof.go.kr'];sources.forEach(item=>assert.ok(allowed.some(domain=>new URL(item.url).hostname===domain||new URL(item.url).hostname.endsWith('.'+domain)),item.url))});
test('institutions are never missing',()=>sources.forEach(item=>assert.ok(item.institution)));
test('official titles are never missing',()=>sources.forEach(item=>assert.ok(item.title)));
test('all source types are official',()=>sources.forEach(item=>assert.equal(item.sourceType,'official')));
test('checkedAt exists and is ISO date',()=>sources.forEach(item=>assert.match(item.checkedAt,/^\d{4}-\d{2}-\d{2}$/)));
test('unknown publication dates remain null',()=>sources.forEach(item=>assert.ok(item.publishedAt===null||/^\d{4}-\d{2}-\d{2}$/.test(item.publishedAt))));
test('license status uses the explicit contract',()=>sources.forEach(item=>assert.ok(['verified','needs-review'].includes(item.license?.status))));
test('unverified licenses are not marked commercially reusable',()=>sources.filter(item=>item.license.status==='needs-review').forEach(item=>{assert.equal(item.license.commercialUse,'unknown');assert.equal(item.license.modification,'unknown')}));
test('no license is incorrectly marked verified',()=>assert.equal(sources.filter(item=>item.license.status==='verified').length,0));
test('all eleven unresolved licenses remain needs review',()=>assert.equal(sources.filter(item=>item.license.status==='needs-review').length,11));
test('taxonomy evidence references are complete',()=>assert.equal(allEvidenceIds.filter(id=>!sourceIds.has(id)).length,0));
test('SEO source references are complete',()=>assert.equal(seoRefs.filter(id=>!sourceIds.has(id)).length,0));
test('every registry source supports at least one evidence id',()=>sources.forEach(item=>assert.ok(item.evidenceFor.length,item.id)));
test('smartfarm temperature and humidity evidence exists',()=>{assert.ok(evidenceFor(smartfarm,'온도').length);assert.ok(evidenceFor(smartfarm,'습도').length)});
test('smartfarm CO2 and solar evidence exists',()=>{assert.ok(evidenceFor(smartfarm,'CO₂').length);assert.ok(evidenceFor(smartfarm,'일사').length)});
test('smartfarm soil moisture evidence exists',()=>assert.ok(evidenceFor(smartfarm,'토양수분').length));
test('smartfarm EC and pH evidence exists',()=>{assert.ok(evidenceFor(smartfarm,'EC').length);assert.ok(evidenceFor(smartfarm,'pH').length)});
test('smartfarm irrigation and nutrient evidence exists',()=>{assert.ok(evidenceFor(smartfarm,'관수').length);assert.ok(evidenceFor(smartfarm,'양액').length)});
test('smartfarm control automation and energy evidence exists',()=>{for(const topic of ['환경제어','자동화','에너지관리','EMS'])assert.ok(evidenceFor(smartfarm,topic).length,topic)});
test('aquafarm core water indicators have evidence',()=>{for(const topic of ['수온','DO','pH','염분'])assert.ok(evidenceFor(aquafarm,topic).length,topic)});
test('aquafarm nitrogen water indicators have evidence',()=>{for(const topic of ['암모니아성질소','아질산성질소','질산성질소'])assert.ok(evidenceFor(aquafarm,topic).length,topic)});
test('RAS evidence exists',()=>assert.ok(evidenceFor(aquafarm,'RAS').includes('nifs-2022-climate-aquaculture-ras')));
test('RAS process evidence covers the requested structure',()=>{for(const topic of ['고형물 제거','용존유기물 처리','pH·이온 조절','생물여과','질산화·탈질','살균','용존가스·산소 관리','재순환'])assert.ok(evidenceFor(aquafarm,topic).length,topic)});
test('aquafarm treatment sensor automation and energy evidence exists',()=>{for(const topic of ['수처리','센서','자동제어','에너지관리','EMS'])assert.ok(evidenceFor(aquafarm,topic).length,topic)});
test('ORP remains in taxonomy',()=>assert.ok(aquafarm.topics.includes('ORP')));
test('ORP remains an aquafarm search term',()=>assert.match(home,/label:'육상 아쿠아팜'[\s\S]*?'ORP'/));
test('ORP is supplementary evidence only',()=>assert.equal(aquafarm.topicPolicies.ORP.evidenceLevel,'supplementary'));
test('ORP SEO is on hold',()=>assert.equal(aquafarm.topicPolicies.ORP.seoEligibility,'hold'));
test('ORP has no promoted source references',()=>assert.deepEqual(aquafarm.topicPolicies.ORP.sourceIds,[]));
test('ORP SEO candidate is also held',()=>{const item=registry.seoCandidates.find(row=>row.id==='aquafarm-orp');assert.equal(item.eligibility,'hold');assert.deepEqual(item.sourceIds,[])});
test('fourteen SEO candidates are eligible',()=>assert.equal(registry.seoCandidates.filter(item=>item.eligibility==='eligible').length,14));
test('RAS is first SEO priority',()=>assert.equal(registry.seoCandidates.find(item=>item.id==='aquafarm-ras').priorityRank,1));
test('aquafarm water quality is second SEO priority',()=>assert.equal(registry.seoCandidates.find(item=>item.id==='aquafarm-water-quality').priorityRank,2));
test('content policy separates official AI and community information',()=>{for(const key of ['officialSourceDisplay','kfarmaiExplanation','aiContent','communityContent','quotationPolicy'])assert.ok(registry.contentPolicy[key])});
test('registry contains no product company or sales records',()=>assert.doesNotMatch(JSON.stringify(registry),/productId|companyId|price|stock|구매하기|장바구니|결제/i));
test('registry contains no secret-looking fields',()=>assert.doesNotMatch(JSON.stringify(registry),/api[_-]?key|service[_-]?role|access[_-]?token|private[_-]?key/i));
test('audit records license uncertainty and no mass copying',()=>{assert.match(audit,/needs-review/);assert.match(audit,/원문을 대량 복제하지 않는다/)});
test('audit records missing handoff source without reconstruction',()=>{assert.match(audit,/source unavailable/);assert.match(audit,/추측해 새 문서를 만들거나 사용자 untracked 파일을 이동하지 않았다/)});

process.stdout.write(`Phase 5B-2 official source registry: ${passed}/${passed} PASS\n`);
