'use strict';
const assert=require('node:assert/strict');const cp=require('node:child_process');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const root=path.resolve(__dirname,'..');const read=file=>fs.readFileSync(path.join(root,file),'utf8');const exists=file=>fs.existsSync(path.join(root,file));
const controlPath='kb/smartfarm-environment-control-automation.html';const energyPath='kb/smartfarm-energy-management.html';const sensorPath='kb/smartfarm-environment-sensors.html';const irrigationPath='kb/smartfarm-irrigation-fertigation.html';
const control=read(controlPath);const energy=read(energyPath);const sensor=read(sensorPath);const irrigation=read(irrigationPath);const pages=[control,energy];const sitemap=read('sitemap.xml');const mfg=read('mfg.html');const workflow=read('.github/workflows/pages.yml');const css=read('static/css/knowledge-v3.css');const taxonomy=JSON.parse(read('data/agri-input-taxonomy.json'));const registry=JSON.parse(read('data/agri-official-sources.json'));
const sourceIds=new Set(registry.sources.map(source=>source.id));const smartfarm=taxonomy.canonicalCategories.find(item=>item.id==='smart-agriculture').children.find(item=>item.id==='smartfarm');
const artifact=fs.mkdtempSync(path.join(os.tmpdir(),'kfarmai-pages-artifact-phase6b-'));let passed=0;function test(name,fn){try{fn();passed++}catch(error){error.message=name+': '+error.message;throw error}}
const titleOf=page=>page.match(/<title>([^<]+)<\/title>/)?.[1]||'';const descriptionOf=page=>page.match(/<meta name="description" content="([^"]+)"/)?.[1]||'';const canonicalOf=page=>page.match(/<link rel="canonical" href="([^"]+)"/)?.[1]||'';const idsOf=page=>(page.match(/data-official-source-ids="([^"]+)"/)?.[1]||'').split(',').filter(Boolean);const articleOf=page=>page.match(/<article class="knowledge-article">([\s\S]*)<\/article>\s*<\/main>/)?.[1]||'';const textOf=html=>html.replace(/<script[\s\S]*?<\/script>/g,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const run=(script,args=[])=>cp.spawnSync(process.execPath,[path.join(root,script),...args],{cwd:root,encoding:'utf8'});

try{
test('environment control automation page exists',()=>assert.ok(exists(controlPath)));
test('energy management page exists',()=>assert.ok(exists(energyPath)));
test('titles are unique and specific',()=>{assert.notEqual(titleOf(control),titleOf(energy));assert.match(titleOf(control),/환경제어·자동화/);assert.match(titleOf(energy),/에너지관리.*EMS/)});
test('descriptions are unique and substantive',()=>{assert.notEqual(descriptionOf(control),descriptionOf(energy));pages.forEach(page=>assert.ok(descriptionOf(page).length>45))});
test('canonical URLs are exact production URLs',()=>{assert.equal(canonicalOf(control),'https://kfarmai.com/'+controlPath);assert.equal(canonicalOf(energy),'https://kfarmai.com/'+energyPath)});
test('canonical URLs contain no preview host',()=>pages.forEach(page=>assert.doesNotMatch(canonicalOf(page),/localhost|127\.0\.0\.1/)));
test('OpenGraph metadata is complete',()=>pages.forEach(page=>{assert.match(page,/<meta property="og:title" content="[^"]+">/);assert.match(page,/<meta property="og:description" content="[^"]+">/);assert.match(page,/<meta property="og:url" content="https:\/\/kfarmai\.com\//)}));
test('each page has exactly one H1',()=>pages.forEach(page=>assert.equal((page.match(/<h1\b/g)||[]).length,1)));
test('visible breadcrumbs include smart agriculture and smartfarm',()=>pages.forEach(page=>{assert.match(page,/<nav class="breadcrumb" aria-label="현재 위치">/);assert.match(page,/스마트농업/);assert.match(page,/스마트팜/)}));
test('Article and BreadcrumbList JSON-LD are present',()=>pages.forEach(page=>{assert.match(page,/"@type":"Article"/);assert.match(page,/"@type":"BreadcrumbList"/)}));
test('JSON-LD parses and kFarmAI remains author',()=>pages.forEach(page=>[...page.matchAll(/<script type="application\/ld\+json">\s*([\s\S]*?)\s*<\/script>/g)].forEach(match=>{const value=JSON.parse(match[1]);if(value['@type']==='Article')assert.equal(value.author.name,'kFarmAI')})));
test('approved favicon is explicit',()=>pages.forEach(page=>assert.match(page,/<link rel="icon" href="\/static\/kfarmai-logo-horizontal\.png">/)));
test('established stylesheet and registry renderer are reused',()=>pages.forEach(page=>{assert.match(page,/\/static\/css\/knowledge-v3\.css/);assert.match(page,/\/static\/js\/agri\/official-source-registry\.js/)}));
test('control page covers the sensor to control flow',()=>['측정','판단','제어','재확인','센서'].forEach(term=>assert.ok(control.includes(term),term)));
test('control page covers environmental mechanisms',()=>['온도·습도','CO₂','환기','일사','차광','냉난방','관수·양액'].forEach(term=>assert.ok(control.includes(term),term)));
test('control page requires manual intervention and records',()=>['수동 개입','수동 전환','비상정지','설정 변경 이력'].forEach(term=>assert.ok(control.includes(term),term)));
test('energy page covers facility energy consumers',()=>['냉난방','환기·차광','관수·양액','센서·제어장치'].forEach(term=>assert.ok(energy.includes(term),term)));
test('energy page explains EMS and environmental linkage',()=>['Energy Management System','환경 조건','설비 운전','에너지 기록'].forEach(term=>assert.ok(energy.includes(term),term)));
test('energy page separates smartfarm and aquafarm context',()=>['온실','시설재배','육상 아쿠아팜','순환펌프','산소공급','수처리'].forEach(term=>assert.ok(energy.includes(term),term)));
test('sensor page links to environment control',()=>assert.match(sensor,/href="\/kb\/smartfarm-environment-control-automation\.html"/));
test('irrigation page links to environment control',()=>assert.match(irrigation,/href="\/kb\/smartfarm-environment-control-automation\.html"/));
test('control page links prior topics and energy',()=>[sensorPath,irrigationPath,energyPath].forEach(url=>assert.ok(control.includes('href="/'+url+'"'),url)));
test('energy page links back to control',()=>assert.ok(energy.includes('href="/'+controlPath+'"')));
test('smartfarm taxonomy links all four pages in sequence',()=>assert.deepEqual(smartfarm.contentLinks.map(item=>item.url),[sensorPath,irrigationPath,controlPath,energyPath]));
test('mfg fallback exposes both Phase 6B pages',()=>[controlPath,energyPath].forEach(url=>assert.ok(mfg.includes(url),url)));
test('sitemap contains new canonicals exactly once and has 179 URLs',()=>{[controlPath,energyPath].forEach(url=>assert.equal(sitemap.split('https://kfarmai.com/'+url).length-1,1,url));assert.equal((sitemap.match(/<loc>/g)||[]).length,179)});
test('all connected source IDs exist',()=>pages.flatMap(idsOf).forEach(id=>assert.ok(sourceIds.has(id),id)));
test('control source coverage uses five official records',()=>{assert.equal(idsOf(control).length,5);['rda-agtech-smartfarm-environment-data','nongsaro-smartfarm-field-applications','nongsaro-smartfarm-introduction','mafra-smartfarm-overview','mafra-smart-agriculture-master-plan'].forEach(id=>assert.ok(idsOf(control).includes(id),id))});
test('energy source coverage uses three official records',()=>{assert.equal(idsOf(energy).length,3);['nongsaro-smartfarm-status','mafra-smartfarm-overview','mafra-smart-agriculture-master-plan'].forEach(id=>assert.ok(idsOf(energy).includes(id),id))});
test('referenced source licenses remain needs-review',()=>pages.flatMap(idsOf).forEach(id=>assert.equal(registry.sources.find(source=>source.id===id).license.status,'needs-review',id)));
test('registry remains the existing eleven-record source of truth',()=>assert.equal(registry.sources.length,11));
test('pages avoid unsupported agronomic and savings figures',()=>pages.forEach(page=>assert.doesNotMatch(articleOf(page),/\d+(?:\.\d+)?\s*(?:°C|도|ppm|%|kWh|원|개월|년|배|리터|L\b)/i)));
test('pages avoid sales and product promotion',()=>pages.forEach(page=>assert.doesNotMatch(page,/구매하기|가격비교|장바구니|결제|추천 제품|최저가|업체 순위|상품 추천/)));
test('automation never removes the need for people',()=>{assert.doesNotMatch(control,/사람이 필요 없|완전 자동|자동 처방 가능/);assert.match(control,/자동화가 작업자의 관찰과 판단을 대신하는 것은 아닙니다/)});
test('energy management makes no savings guarantee',()=>{assert.doesNotMatch(energy,/\d+(?:\.\d+)?\s*%\s*절감|절감됩니다|절감할 수 있습니다|투자회수\s*(?:\d|약|이내)/);assert.match(energy,/절감효과를 보장[^.]*아닙니다/);assert.match(energy,/절감률[^.]*제시하지 않습니다/)});
test('pages are substantive rather than thin content',()=>pages.forEach(page=>assert.ok(textOf(articleOf(page)).length>2100,textOf(articleOf(page)).length)));
test('heading hierarchy never skips levels',()=>pages.forEach(page=>{const levels=[...page.matchAll(/<h([1-3])\b/g)].map(match=>Number(match[1]));assert.equal(levels[0],1);for(let i=1;i<levels.length;i++)assert.ok(levels[i]-levels[i-1]<=1)}));
test('core internal links resolve locally',()=>pages.forEach(page=>[...page.matchAll(/href="(\/[^"]+)"/g)].map(match=>match[1].split(/[?#]/)[0]).filter(url=>!url.startsWith('/api/')).forEach(url=>{const relative=url==='/'?'index.html':url.replace(/^\//,'');const target=relative.endsWith('/')?relative+'index.html':relative;assert.ok(exists(target),url)})));
test('focus and long URL accessibility contracts remain active',()=>{assert.match(css,/a:focus-visible/);assert.match(css,/\.source-card a[\s\S]*overflow-wrap:\s*anywhere/)});
test('ORP remains supplementary and held without a page',()=>{const aquafarm=taxonomy.canonicalCategories.find(item=>item.id==='smart-agriculture').children.find(item=>item.id==='land-aquafarm');assert.equal(aquafarm.topicPolicies.ORP.evidenceLevel,'supplementary');assert.equal(aquafarm.topicPolicies.ORP.seoEligibility,'hold');assert.equal(exists('kb/aquafarm-orp.html'),false);assert.doesNotMatch(sitemap,/orp/i)});
const build=run('scripts/pages/build-pages-artifact.cjs',[`--output=${artifact}`]);
test('allowlist artifact builder succeeds',()=>assert.equal(build.status,0,build.stderr));
const verify=run('scripts/pages/verify-pages-artifact.cjs',[artifact]);
test('artifact security verifier succeeds',()=>assert.equal(verify.status,0,verify.stderr));
test('both new pages are included in the artifact',()=>[controlPath,energyPath].forEach(file=>assert.ok(fs.existsSync(path.join(artifact,file)),file)));
test('internal development paths remain absent from artifact',()=>['supabase','worker','tests','docs','.github','AGENTS.md','KFarmAI_HISTORY_HANDOFF_20260919.md','package.json'].forEach(file=>assert.ok(!fs.existsSync(path.join(artifact,file)),file)));
test('workflow retains builder allowlist and fail-fast guard',()=>{assert.match(workflow,/build-pages-artifact\.cjs/);assert.match(workflow,/verify-pages-artifact\.cjs/);assert.doesNotMatch(workflow,/rsync\s+-av|\.\/\s+_site\//)});
process.stdout.write('Phase 6B smartfarm control and energy contracts: '+passed+'/'+passed+' PASS\n');
}finally{fs.rmSync(artifact,{recursive:true,force:true})}
