import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';import fs from 'node:fs';import http from 'node:http';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const chromePath='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
class CdpSocket{constructor(url){this.url=url;this.id=0;this.pending=new Map;this.listeners=new Map}open(){return new Promise((resolve,reject)=>{this.socket=new WebSocket(this.url);this.socket.addEventListener('open',resolve,{once:true});this.socket.addEventListener('error',reject,{once:true});this.socket.addEventListener('message',event=>this.receive(JSON.parse(event.data)))})}send(method,params={}){const id=++this.id;const promise=new Promise((resolve,reject)=>this.pending.set(id,{resolve,reject}));this.socket.send(JSON.stringify({id,method,params}));return promise}on(method,callback){const rows=this.listeners.get(method)||[];rows.push(callback);this.listeners.set(method,rows)}once(method){return new Promise(resolve=>{const callback=params=>{this.listeners.set(method,(this.listeners.get(method)||[]).filter(item=>item!==callback));resolve(params)};this.on(method,callback)})}receive(message){if(message.id){const pending=this.pending.get(message.id);if(!pending)return;this.pending.delete(message.id);message.error?pending.reject(new Error(message.error.message)):pending.resolve(message.result);return}for(const callback of this.listeners.get(message.method)||[])callback(message)}close(){this.socket?.close()}}
const port=18789,debugPort=19225,profileDir=fs.mkdtempSync(path.join(os.tmpdir(),'kfarmai-phase4c-chrome-'));
if(!fs.existsSync(chromePath))throw new Error('Chrome executable is required for image privacy verification');
const server=http.createServer((request,response)=>{const url=new URL(request.url||'/',`http://127.0.0.1:${port}`);if(url.pathname==='/'){response.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});response.end('<!doctype html><canvas></canvas><script src="/static/js/community/question-draft.js"></script>');return;}const target=path.resolve(root,decodeURIComponent(url.pathname).replace(/^\/+/,''));if(!target.startsWith(root+path.sep)||!fs.existsSync(target)){response.writeHead(404);response.end();return;}response.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8'});fs.createReadStream(target).pipe(response)});
const chrome=spawn(chromePath,['--headless=new','--disable-gpu','--no-first-run',`--remote-debugging-port=${debugPort}`,`--user-data-dir=${profileDir}`,'about:blank'],{stdio:'ignore',windowsHide:true});let socket;
try{
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve)});
  for(let i=0;i<50;i++){try{if((await fetch(`http://127.0.0.1:${debugPort}/json/version`)).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
  const target=await fetch(`http://127.0.0.1:${debugPort}/json/new?about:blank`,{method:'PUT'}).then(r=>r.json());socket=new CdpSocket(target.webSocketDebuggerUrl);await socket.open();await socket.send('Page.enable');const loaded=socket.once('Page.loadEventFired');await socket.send('Page.navigate',{url:`http://127.0.0.1:${port}/`});await loaded;
  const result=await evaluate(socket,`(async()=>{
    const canvas=document.querySelector('canvas');canvas.width=40;canvas.height=20;const context=canvas.getContext('2d');context.fillStyle='#298a52';context.fillRect(0,0,40,20);
    const jpeg=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));const raw=new Uint8Array(await jpeg.arrayBuffer());const meta=new TextEncoder().encode('Exif\\0\\0GPSLatitude');const segment=new Uint8Array(4+meta.length);segment.set([255,225,0,meta.length+2],0);segment.set(meta,4);const marked=new Uint8Array(raw.length+segment.length);marked.set(raw.slice(0,2),0);marked.set(segment,2);marked.set(raw.slice(2),2+segment.length);
    const original=new File([marked],'farm-gps-original.jpg',{type:'image/jpeg'});const safe=await KFQuestionDraft.prepareForUpload(original);const text=new TextDecoder('latin1').decode(await safe.arrayBuffer());const id=await KFQuestionDraft.saveImage(original);const loaded=await KFQuestionDraft.loadImage(id);await KFQuestionDraft.removeImage(id);const removed=await KFQuestionDraft.loadImage(id);
    const pending={source:'ai_diagnosis',crop:'고추',symptoms:['잎말림'],suggestedTags:['고추','잎말림'],summary:'원인 후보는 확인이 필요합니다.',imageDraftId:id};localStorage.setItem('kfarmai_pending_question',JSON.stringify(pending));const restored=JSON.parse(localStorage.getItem('kfarmai_pending_question'));let permanentUploads=0;const publish=confirmed=>{if(confirmed)permanentUploads+=1};publish(false);
    return {sourceHadExif:new TextDecoder('latin1').decode(marked).includes('Exif'),safeHasExif:text.includes('Exif'),safeHasGps:text.includes('GPSLatitude'),renamed:safe.name!=='farm-gps-original.jpg'&&!safe.name.includes('gps-original'),safeType:safe.type,loaded:Boolean(loaded),loadedRenamed:Boolean(loaded&&!loaded.name.includes('gps-original')),removed:removed===null,structuredDraft:restored.source==='ai_diagnosis'&&restored.crop==='고추'&&restored.symptoms[0]==='잎말림'&&restored.suggestedTags.length===2,noPermanentBeforeConfirm:permanentUploads===0};
  })()`);
  assert.equal(result.sourceHadExif,true);assert.equal(result.safeHasExif,false);assert.equal(result.safeHasGps,false);assert.equal(result.renamed,true);assert.equal(result.safeType,'image/jpeg');assert.equal(result.loaded,true);assert.equal(result.loadedRenamed,true);assert.equal(result.removed,true);assert.equal(result.structuredDraft,true);assert.equal(result.noPermanentBeforeConfirm,true);
  process.stdout.write('Phase 4C AI draft/image privacy browser: 10/10 PASS\n');
}finally{try{await socket?.send('Browser.close')}catch{}socket?.close();await new Promise(r=>server.close(r));if(!chrome.killed)chrome.kill();await new Promise(r=>setTimeout(r,200));const resolved=path.resolve(profileDir);if(resolved.startsWith(path.resolve(os.tmpdir())+path.sep))fs.rmSync(resolved,{recursive:true,force:true})}
async function evaluate(client,expression){const result=await client.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.text||'browser evaluation failed');return result.result.value}
